import type { SectionID } from './configEditorTypes'

export const SECTION_META: Record<SectionID, { en: string; zh: string; descEn: string; descZh: string }> = {
  general: {
    en: 'General',
    zh: '通用',
    descEn: 'Core settings: default model, agent, shell, sharing and updates.',
    descZh: '核心设置：默认模型、默认 agent、shell、分享与自动更新。',
  },
  server: {
    en: 'Server',
    zh: '服务',
    descEn: 'Options for the opencode serve and web commands.',
    descZh: 'opencode serve 和 web 命令的服务端选项。',
  },
  commands: {
    en: 'Commands',
    zh: '自定义命令',
    descEn: 'Custom slash commands. Each command has a prompt template.',
    descZh: '自定义斜杠命令，每条命令带一个 prompt 模板。',
  },
  skills: {
    en: 'Skills & References',
    zh: '技能与引用',
    descEn: 'Extra skill folders/URLs and named @ references.',
    descZh: '额外的技能目录/URL，以及可用 @ 提及的命名引用。',
  },
  plugins: {
    en: 'Plugins',
    zh: '插件',
    descEn: 'Plugin package specs or local plugin files, with optional options.',
    descZh: '插件包名或本地插件文件，可附带配置项。',
  },
  providers: {
    en: 'Providers & Models',
    zh: '渠道与模型',
    descEn: 'Custom provider configuration and per-model overrides.',
    descZh: '自定义渠道（provider）配置以及单个模型的覆盖项。',
  },
  agents: {
    en: 'Agents',
    zh: 'Agent',
    descEn: 'Built-in and custom agent overrides (model, prompt, permissions).',
    descZh: '内置与自定义 agent 的覆盖（模型、提示词、权限等）。',
  },
  mcp: {
    en: 'MCP Servers',
    zh: 'MCP 服务',
    descEn: 'Configure MCP servers with a local command or remote URL.',
    descZh: '配置本地命令或远程 URL 的 MCP 服务。',
  },
  permissions: {
    en: 'Permissions',
    zh: '权限',
    descEn: 'Default action (ask/allow/deny) per tool, with optional pattern rules.',
    descZh: '每个工具的默认动作（询问/允许/拒绝），可按 pattern 细分。',
  },
  formatters: {
    en: 'Formatters',
    zh: '格式化器',
    descEn: 'Enable built-in formatters or override individual formatter entries.',
    descZh: '启用内置格式化器，或覆盖单个格式化器配置。',
  },
  lsp: {
    en: 'LSP Servers',
    zh: 'LSP 服务',
    descEn: 'Enable built-in language servers or define custom ones.',
    descZh: '启用内置语言服务器，或定义自定义 LSP。',
  },
  attachments: {
    en: 'Attachments',
    zh: '附件',
    descEn: 'Image attachment limits and auto-resize behavior.',
    descZh: '图片附件的尺寸限制与自动缩放行为。',
  },
  runtime: {
    en: 'Runtime',
    zh: '运行时',
    descEn: 'Tool output limits, context compaction, watcher and enterprise.',
    descZh: '工具输出限制、上下文压缩、文件监听和企业设置。',
  },
  experimental: {
    en: 'Experimental',
    zh: '实验性',
    descEn: 'Experimental flags that may change or be removed in future versions.',
    descZh: '实验性开关，未来版本可能变化或移除。',
  },
  compatibility: {
    en: 'Compatibility',
    zh: '兼容',
    descEn: 'Deprecated or compatibility fields that still exist in opencode.json.',
    descZh: '仍存在于 opencode.json 中的废弃字段或兼容字段。',
  },
  advanced: {
    en: 'Unknown / Future',
    zh: '未知/未来字段',
    descEn: 'Top-level fields not recognized by the current schema. They may be invalid or from a newer opencode version.',
    descZh: '当前 schema 不认识的顶层字段，可能无效，也可能来自更新版本的 opencode。',
  },
}

export const SECTION_IDS: SectionID[] = [
  'general',
  'server',
  'commands',
  'skills',
  'plugins',
  'providers',
  'agents',
  'mcp',
  'permissions',
  'formatters',
  'lsp',
  'attachments',
  'runtime',
  'experimental',
  'compatibility',
  'advanced',
]

export const KNOWN_ROOT_KEYS = new Set([
  '$schema',
  'shell',
  'logLevel',
  'server',
  'command',
  'skills',
  'references',
  'reference',
  'watcher',
  'snapshot',
  'plugin',
  'share',
  'autoshare',
  'autoupdate',
  'disabled_providers',
  'enabled_providers',
  'model',
  'small_model',
  'default_agent',
  'subagent_depth',
  'username',
  'mode',
  'agent',
  'provider',
  'mcp',
  'formatter',
  'lsp',
  'instructions',
  'layout',
  'permission',
  'tools',
  'attachment',
  'enterprise',
  'tool_output',
  'compaction',
  'experimental',
])

export const PERMISSION_TOOLS: { tool: string; pattern: boolean; en: string; zh: string }[] = [
  { tool: 'read', pattern: true, en: 'Read files', zh: '读取文件' },
  { tool: 'edit', pattern: true, en: 'Edit / write files', zh: '编辑/写入文件' },
  { tool: 'glob', pattern: true, en: 'Find files by glob', zh: '按通配符查找文件' },
  { tool: 'grep', pattern: true, en: 'Search file contents', zh: '搜索文件内容' },
  { tool: 'list', pattern: true, en: 'List directories', zh: '列出目录' },
  { tool: 'bash', pattern: true, en: 'Run shell commands', zh: '执行 shell 命令' },
  { tool: 'task', pattern: true, en: 'Spawn sub-agents', zh: '启动子 agent' },
  { tool: 'external_directory', pattern: true, en: 'Access dirs outside workspace', zh: '访问工作区外目录' },
  { tool: 'lsp', pattern: true, en: 'Language server actions', zh: '语言服务器操作' },
  { tool: 'skill', pattern: true, en: 'Load skills', zh: '加载技能' },
  { tool: 'todowrite', pattern: false, en: 'Write todo list', zh: '写入待办列表' },
  { tool: 'question', pattern: false, en: 'Ask the user questions', zh: '向用户提问' },
  { tool: 'webfetch', pattern: false, en: 'Fetch web pages', zh: '抓取网页' },
  { tool: 'websearch', pattern: false, en: 'Search the web', zh: '联网搜索' },
  { tool: 'doom_loop', pattern: false, en: 'Doom loop guard', zh: '死循环保护' },
]

export const PERMISSION_ACTIONS = ['ask', 'allow', 'deny']
export const MODEL_STATUS = ['active', 'alpha', 'beta', 'deprecated']
export const MODALITIES = ['text', 'audio', 'image', 'video', 'pdf']
