use std::{collections::BTreeMap, path::Path};

use tokio::fs;

use crate::{
    config::{Config, PREVIEW_FILE, ROUTES_FILE},
    scanner,
    state::RouteInfo,
};

pub(crate) async fn write_map(
    config: &Config,
    routes: &BTreeMap<String, RouteInfo>,
) -> Result<(), String> {
    ensure_parent_dir(ROUTES_FILE).await?;

    let mut lines = vec!["# Dynamic routes (auto generated by router)".to_string()];

    for (token, info) in routes {
        lines.push(format!("@route_{token} path /p/{token} /p/{token}/*"));
        lines.push(format!("handle @route_{token} {{"));
        lines.push(format!("\turi strip_prefix /p/{token}"));
        lines.push(format!(
            "\treverse_proxy {}:{}",
            config.target_container(),
            info.port
        ));
        lines.push("}".to_string());
        lines.push(String::new());
    }

    fs::write(ROUTES_FILE, lines.join("\n") + "\n")
        .await
        .map_err(|err| err.to_string())
}

pub(crate) async fn write_preview_conf(config: &Config, port: Option<u16>) -> Result<(), String> {
    ensure_parent_dir(PREVIEW_FILE).await?;

    let body = match port {
        Some(port) => format!(
            "# Preview proxy (auto generated by router)\nreverse_proxy {}:{}\n",
            config.target_container(),
            port
        ),
        None => concat!(
            "# Preview proxy (no port selected)\n",
            "respond \"No preview port configured. Set one from the Routes panel.\" 503\n"
        )
        .to_string(),
    };

    fs::write(PREVIEW_FILE, body)
        .await
        .map_err(|err| err.to_string())
}

pub(crate) async fn reload_gateway() -> Result<(), String> {
    scanner::run_cmd(&["caddy", "reload", "--config", "/etc/caddy/Caddyfile"]).await?;
    Ok(())
}

async fn ensure_parent_dir(path: &str) -> Result<(), String> {
    let Some(parent) = Path::new(path).parent() else {
        return Ok(());
    };

    fs::create_dir_all(parent)
        .await
        .map_err(|err| err.to_string())
}
