// ============================================
// build-bridge.mjs
// Bundle the Pi bridge server (server/src/index.ts) into a single
// ESM file that ships inside the Tauri app resources. The desktop
// app spawns it with the user's own Node.js runtime.
//
//   node scripts/build-bridge.mjs
//   → src-tauri/resources/pi-bridge/index.mjs
// ============================================
import { build } from 'esbuild'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const outdir = path.join(root, 'src-tauri', 'resources', 'pi-bridge')
const outfile = path.join(outdir, 'index.mjs')

fs.mkdirSync(outdir, { recursive: true })

// ESM banner: provide CJS interop helpers some dependencies expect.
const banner = [
  '// Pi Agent bridge — bundled single-file server (generated by scripts/build-bridge.mjs)',
  "import { createRequire as __piCreateRequire } from 'node:module';",
  "import { fileURLToPath as __piFileURLToPath } from 'node:url';",
  "import { dirname as __piDirname } from 'node:path';",
  'const require = __piCreateRequire(import.meta.url);',
  'const __filename = __piFileURLToPath(import.meta.url);',
  'const __dirname = __piDirname(__filename);',
].join('\n')

await build({
  entryPoints: [path.join(root, 'server', 'src', 'index.ts')],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  outfile,
  // node-pty is a native addon; keep it external. The bridge falls back
  // to a stub terminal when it cannot be resolved at runtime.
  external: ['node-pty'],
  sourcemap: false,
  minify: false,
  keepNames: true,
  logLevel: 'info',
  banner: { js: banner },
})

const sizeMb = (fs.statSync(outfile).size / 1024 / 1024).toFixed(1)
console.log(`[build-bridge] wrote ${path.relative(root, outfile)} (${sizeMb} MB)`)
