// ============================================
// build-bridge.mjs
// Bundle the Pi bridge server (server/src/index.ts) into a single
// ESM file that ships inside the Tauri app resources. The desktop
// app spawns it with the user's own Node.js runtime.
//
//   node scripts/build-bridge.mjs
//   → src-tauri/resources/pi-bridge/index.mjs
// ============================================
import { build } from 'esbuild'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const outdir = path.join(root, 'src-tauri', 'resources', 'pi-bridge')
const outfile = path.join(outdir, 'index.mjs')

fs.mkdirSync(outdir, { recursive: true })

// ESM banner: provide CJS interop helpers some dependencies expect.
const banner = [
  '// Pi Agent bridge — bundled single-file server (generated by scripts/build-bridge.mjs)',
  "import { createRequire as __piCreateRequire } from 'node:module';",
  "import { fileURLToPath as __piFileURLToPath } from 'node:url';",
  "import { dirname as __piDirname } from 'node:path';",
  'const require = __piCreateRequire(import.meta.url);',
  'const __filename = __piFileURLToPath(import.meta.url);',
  'const __dirname = __piDirname(__filename);',
].join('\n')

await build({
  entryPoints: [path.join(root, 'server', 'src', 'index.ts')],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  outfile,
  // node-pty is a native addon; keep it external. The bridge falls back
  // to a stub terminal when it cannot be resolved at runtime.
  external: ['node-pty'],
  sourcemap: false,
  minify: false,
  keepNames: true,
  logLevel: 'info',
  banner: { js: banner },
})

// ============================================
// pi 扩展加载的运行时支持文件
//
// 单文件 bundle 破坏了 SDK 内部 jiti 的路径假设：
// 1. 扩展依赖（typebox 等）以 bundle 目录为根解析
//    → 拷贝小型运行时模块集到 resources/pi-bridge/node_modules
// 2. '@earendil-works/pi-coding-agent' 别名指向 <bundle>/../../index.js
//    → 生成 src-tauri/index.js 桥接文件，重定向到 globalThis 上的 SDK
// ============================================
const serverModules = path.join(root, 'server', 'node_modules')
const sdkNested = path.join(serverModules, '@earendil-works', 'pi-coding-agent', 'node_modules')

/** pi 扩展加载时需要的模块（实测收敛的集合） */
const EXTENSION_RUNTIME_MODULES = [
  'typebox',
  'partial-json',
  'get-east-asian-width',
  '@earendil-works/pi-agent-core',
  '@earendil-works/pi-ai',
  '@earendil-works/pi-tui',
]

function findModuleSource(name) {
  const candidates = [path.join(sdkNested, name), path.join(serverModules, name)]
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate
  }
  return null
}

const modulesDest = path.join(outdir, 'node_modules')
fs.rmSync(modulesDest, { recursive: true, force: true })
const copied = []
for (const name of EXTENSION_RUNTIME_MODULES) {
  const source = findModuleSource(name)
  if (!source) {
    console.warn(`[build-bridge] module not found, skipped: ${name}`)
    continue
  }
  fs.cpSync(source, path.join(modulesDest, name), { recursive: true })
  copied.push(name)
}
console.log(`[build-bridge] extension runtime modules: ${copied.join(', ')}`)

// 别名桥接文件：扩展 import '@earendil-works/pi-coding-agent' 时
// 拿到 bundle 内的同一份 SDK（避免双实例）
const stubPath = path.join(root, 'src-tauri', 'index.js')
fs.writeFileSync(
  stubPath,
  [
    '// Generated by scripts/build-bridge.mjs — do not edit.',
    "// jiti alias target for '@earendil-works/pi-coding-agent' used by pi extensions.",
    '// The bridge exposes the bundled SDK on globalThis at startup (server/src/index.ts).',
    'module.exports = globalThis.__PI_SDK__ || {};',
    '',
  ].join('\n'),
)
console.log('[build-bridge] wrote src-tauri/index.js (SDK alias stub)')

const sizeMb = (fs.statSync(outfile).size / 1024 / 1024).toFixed(1)
console.log(`[build-bridge] wrote ${path.relative(root, outfile)} (${sizeMb} MB)`)
