// ============================================
// API Types - 统一导出（本地类型，不再依赖 @opencode-ai/sdk）
// ============================================

export type {
  // Common
  ErrorInfo,
  ProviderAuthError,
  UnknownError,
  MessageOutputLengthError,
  MessageAbortedError,
  APIError,
  // Session
  Session,
  SessionStatus,
  SessionStatusMap,
  SessionSummary,
  SessionShare,
  SessionRevert,
  SessionListParams,
  SessionCreateParams,
  SessionUpdateParams,
  SessionForkParams,
  // Message
  Message,
  UserMessage,
  AssistantMessage,
  MessageSummary,
  MessageWithParts,
  Part,
  TextPart,
  ReasoningPart,
  ToolPart,
  FilePart,
  FileSource,
  FileSourceType,
  AgentPart,
  StepStartPart,
  StepFinishPart,
  SnapshotPart,
  PatchPart,
  SubtaskPart,
  RetryPart,
  CompactionPart,
  TextPartInput,
  FilePartInput,
  AgentPartInput,
  SubtaskPartInput,
  // Model
  Model,
  ModelStatus,
  ModelLimit,
  ModelCapabilities,
  ModelIOCapabilities,
  Provider,
  ProvidersResponse,
  ProviderAuthMethod,
  ProviderAuthAuthorization,
  // Permission
  PermissionToolInfo,
  PermissionRequest,
  PermissionReply,
  QuestionOption,
  QuestionInfo,
  QuestionRequest,
  QuestionAnswer,
  // File
  FileNode,
  FileNodeType,
  FileContent,
  FileDiff,
  FileStatusItem,
  FilePatch,
  PatchHunk,
  Symbol as Symbol,
  SymbolLocation,
  SymbolRange,
  TextSearchMatch,
  // Project
  Project,
  ProjectIcon,
  ProjectCommands,
  ProjectUpdateParams,
  Path as PathResponse,
  // Agent
  Agent,
  AgentMode,
  AgentPermission,
  // Event
  GlobalEvent,
  EventType,
  EventCallbacks,
  ServerConnectedPayload,
  SessionIdlePayload,
  SessionErrorPayload,
  SessionStatusPayload,
  SessionDiffPayload,
  PartDeltaPayload,
  PartRemovedPayload,
  PermissionRepliedPayload,
  QuestionRepliedPayload,
  QuestionRejectedPayload,
  TodoItem,
  TodoUpdatedPayload,
  WorktreeReadyPayload,
  WorktreeFailedPayload,
  VcsBranchUpdatedPayload,
  // Config
  Config,
  LogLevel,
  ServerConfig,
  PermissionConfig,
  PermissionActionConfig,
  PermissionObjectConfig,
  PermissionRuleConfig,
  AgentConfig,
  ProviderConfig,
  McpLocalConfig,
  McpOAuthConfig,
  McpRemoteConfig,
  LayoutConfig,
  // MCP
  MCPStatus,
  MCPStatusConnected,
  MCPStatusDisabled,
  MCPStatusFailed,
  MCPStatusNeedsAuth,
  MCPStatusNeedsClientRegistration,
  MCPResource,
  MCPStatusResponse,
  McpServerConfig,
  // Skill
  Skill,
  SkillList,
  // PTY
  Pty,
  PtySize,
  PtyCreateParams,
  PtyUpdateParams,
  // VCS
  VcsInfo,
  VcsDiffMode,
  // Worktree
  Worktree,
  WorktreeCreateInput,
  WorktreeRemoveInput,
  WorktreeResetInput,
  // Tool
  ToolIDs,
  ToolList,
  ToolListItem,
} from './generated'

export { EventTypes } from './generated'
